import { isCentralApprovalCustomer } from "@/lib/approvalPipeline";
import type {
  BannerAsset,
  CampaignPerformance,
  ChannelExecutionOutcomeRollup,
  ChannelType,
  Customer,
  FeedbackFollowUpCustomer,
  MessageTemplate,
  PipelineExecutionOutcome,
  PipelineExecutionOutcomeReport,
} from "@/types";

export const customers: Customer[] = [
  {
    customerId: "C-10028491",
    customerName: "김서연",
    segment: "VIP",
    ageGroup: "40대",
    branchName: "강남중앙지점",
    assetLevel: "초고자산",
    recentActivityScore: 88,
    appLoginScore: 92,
    smsResponseScore: 78,
    pushOpenScore: 85,
    tmSuitabilityScore: 91,
    careTaskFeatures: ["마이케어: 투자상품 상담 이력", "TM 응답률 상위 15%"],
    transactionFeatures: ["최근 3개월 예금 잔액 +12%", "급여이체 유입 확인"],
    targetTaskName: "만기·재예치 통합 캠페인 (Q2)",
    targetReason:
      "최근 3개월 예금 잔액이 꾸준히 증가했고 급여이체 유입이 확인되어 투자 여력이 높은 것으로 판단됩니다. 기존 마이케어 과제에서 TM 반응률이 높아 복합 상품 설명이 효과적일 가능성이 큽니다.",
    featureSummary: "예금↑·급여이체·TM 반응 우수",
    recommendedChannels: [
      { channel: "영업점TM", score: 94, reason: "고가치 고객, 복합 설명 필요 상품, 최근 상담 이력 존재" },
      { channel: "앱푸쉬", score: 86, reason: "앱 로그인 활성, 푸쉬 수신동의 고객" },
      { channel: "SOL배너", score: 72, reason: "앱 활동성 높고 클릭 기반 유입 예상" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message:
          "[OO은행] 김서연 고객님, 맞춤 자산 리밸런싱 안내드립니다. 상담 예약: 앱 > 고객센터",
        compliance: "사용가능",
        scheduledDate: "2025-04-02",
        reason: "유사 세그먼트에서 높은 오픈율을 보인 템플릿",
        templateId: "MSG-T-8821",
      },
      push: {
        templateOrNew: "기존템플릿",
        title: "자산 리밸런싱 제안",
        body: "시장 변동에 맞춰 포트폴리오를 점검해 보세요.",
        landingUrl: "https://sol.bank.example/premium/rebalance",
        emoji: "📈",
        imageInfo: "라이프스타일 일러스트 A-12",
        fitScore: 88,
        compliance: "사용가능",
        scheduledDate: "2025-04-02",
      },
      banner: {
        line1: "VIP 맞춤 자산 점검",
        line2: "지금 앱에서 상담을 예약하세요",
        imageLabel: "프리미엄 라운지",
        imageUrl: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&q=80",
        landingUrl: "https://sol.bank.example/vip/lounge",
        reason: "클릭률 높은 테마와 고객 세그먼트 일치",
        expectedCtr: "4.2%",
      },
      tm: {
        briefing:
          "예금 증가와 급여이체로 여유 자금이 형성된 상태입니다. 기존 투자상품 보유 비중을 확인하고 리밸런싱 니즈를 탐색하세요.",
        consultPoints: ["세제 혜택 상품 연계", "리스크 성향 재확인", "가족 자녀 교육자금 목표"],
        script:
          "안녕하세요 김서연 고객님, 최근 자산 흐름이 안정적으로 보입니다. 시장 변동에 맞춰 포트폴리오를 함께 점검해 드리고자 연락드렸습니다. 잠시 상담 가능하실까요?",
        recommendedSms:
          "[OO은행] 고객님 맞춤 자산 점검 안내. 방문 상담 예약: 앱 홈 > 상담예약",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-02",
    expectedPerformance: "TM 전환 예상 32% / 푸쉬 오픈 41%",
    feedbackSignals: ["TM 성공 시 펀드 계약 전환율 상승 패턴"],
    priority: "P1",
  },
  {
    customerId: "C-10030122",
    customerName: "이도윤",
    segment: "성장형",
    ageGroup: "30대",
    branchName: "송파금융센터",
    assetLevel: "중상",
    recentActivityScore: 76,
    appLoginScore: 81,
    smsResponseScore: 84,
    pushOpenScore: 62,
    tmSuitabilityScore: 55,
    careTaskFeatures: ["마이케어: 카드 이용 증가"],
    transactionFeatures: ["만기 도래 28일 전(정기예금)", "앱 접속 빈도 +35%"],
    targetTaskName: "만기·재예치 통합 캠페인 (Q2)",
    targetReason:
      "정기예금 만기가 임박했고 앱 접속이 늘어 비대면 안내 적합도가 높습니다. 문자 반응률이 푸쉬 대비 우수합니다.",
    featureSummary: "만기임박·앱활성·문자 반응 우수",
    recommendedChannels: [
      { channel: "문자메시지", score: 90, reason: "최근 문자 반응률 우수, 앱푸쉬 미열람 비율 상대적으로 높음" },
      { channel: "SOL배너", score: 78, reason: "앱 활동성 높고 클릭 기반 유입 예상" },
      { channel: "앱푸쉬", score: 68, reason: "푸쉬 수신동의는 되어 있으나 오픈율 개선 필요" },
    ],
    primaryChannel: "문자메시지",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message:
          "[OO은행] 이도윤 고객님, 예금 만기가 다가옵니다. 우대 금리 재예치/이전 상품을 앱에서 비교해 보세요.",
        compliance: "사용가능",
        scheduledDate: "2025-04-01",
        reason: "만기 알림 템플릿 RAG 매칭 상위",
        templateId: "MSG-T-4410",
      },
      push: {
        templateOrNew: "신규생성",
        title: "만기 자금, 어떻게 할까요?",
        body: "만기 30일 전, 맞춤 상품을 추천해 드려요.",
        landingUrl: "https://sol.bank.example/maturity",
        emoji: "⏳",
        imageInfo: "캘린더 아이콘 세트 B",
        fitScore: 64,
        compliance: "심사필요",
        scheduledDate: "2025-04-08",
      },
      banner: {
        line1: "만기 자금 맞춤 비교",
        line2: "한 번에 우대 조건 확인",
        imageLabel: "금융 계산기",
        imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&q=80",
        landingUrl: "https://sol.bank.example/compare",
        reason: "만기 관련 클릭률 높은 배너 유형",
        expectedCtr: "3.1%",
      },
      tm: {
        briefing: "만기 자금이 형성될 예정으로 재예치 vs 이전 상품 비교 니즈가 예상됩니다.",
        consultPoints: ["세금 우대", "CMA 연계"],
        script: "만기 예정 자금의 용도와 기간을 확인 후 맞춤 상품을 안내드리겠습니다.",
        recommendedSms: "[OO은행] 만기 안내. 자세한 비교는 앱에서 확인 가능합니다.",
      },
    },
    complianceStatus: "심사필요",
    scheduledDate: "2025-04-01",
    expectedPerformance: "문자 응답 18% / 배너 CTR 3.1%",
    feedbackSignals: ["문자 CTR 상위, 푸쉬 오픈은 하위 quartile"],
    priority: "P2",
  },
  {
    customerId: "C-10019873",
    customerName: "박민준",
    segment: "안정형",
    ageGroup: "50대",
    branchName: "분당역지점",
    assetLevel: "중간",
    recentActivityScore: 62,
    appLoginScore: 58,
    smsResponseScore: 71,
    pushOpenScore: 48,
    tmSuitabilityScore: 88,
    careTaskFeatures: ["마이케어: 연금저축 납입 중단 경고"],
    transactionFeatures: ["투자성 상품 미보유", "정기적 적금 납입 유지"],
    targetTaskName: "만기·재예치 통합 캠페인 (Q2)",
    targetReason:
      "투자성 상품은 없으나 적금은 유지 중입니다. 연금 납입이 끊겨 장기 목표 이탈 위험이 있어 TM으로 동기 부여가 효과적입니다.",
    featureSummary: "투자미보유·연금 이탈 위험·TM 적합",
    recommendedChannels: [
      { channel: "영업점TM", score: 92, reason: "고령층, 설명 충분히 필요, 최근 방문 이력 있음" },
      { channel: "문자메시지", score: 74, reason: "문자 반응률 양호" },
      { channel: "앱푸쉬", score: 45, reason: "푸쉬 오픈율 낮음" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      sms: {
        templateOrNew: "신규생성",
        message:
          "[OO은행] 박민준 고객님, 연금저축 납입이 멈춰 있어 노후 준비 점검을 권해 드립니다.",
        compliance: "심사필요",
        scheduledDate: "2025-04-05",
        reason: "기존 템플릿과 톤은 유사하나 문구 커스터마이징 필요",
      },
      push: {
        templateOrNew: "신규생성",
        title: "연금 납입 점검",
        body: "끊긴 납입, 다시 이어가는 방법을 알려드려요.",
        landingUrl: "https://sol.bank.example/pension",
        emoji: "🏦",
        imageInfo: "연금 아이콘 팩",
        fitScore: 52,
        compliance: "검토중",
        scheduledDate: "2025-04-09",
      },
      banner: {
        line1: "연금, 다시 채우는 방법",
        line2: "세제 혜택까지 한눈에",
        imageLabel: "가족 실루엣",
        imageUrl: "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=400&q=80",
        landingUrl: "https://sol.bank.example/pension/info",
        reason: "안정형 세그먼트에서 반응 좋은 톤",
        expectedCtr: "2.4%",
      },
      tm: {
        briefing: "연금 납입이 중단되어 장기 목표 달성 리스크가 있습니다. 세제 혜택과 복리 효과를 중심으로 설명 권장.",
        consultPoints: ["납입 재개 금액 시뮬레이션", "노후 목표 금액 재설정"],
        script:
          "연금저축은 작은 금액이라도 꾸준히 이어가실 때 가장 큰 힘이 됩니다. 부담 없는 금액부터 재개를 도와드릴까요?",
        recommendedSms: "[OO은행] 연금저축 납입 상태를 확인해 주세요. 상담 예약: 앱",
      },
    },
    complianceStatus: "심사필요",
    scheduledDate: "2025-04-05",
    expectedPerformance: "TM 상담 완료율 예상 45%",
    feedbackSignals: ["TM 성공 시 연금 재납입률 높음"],
    priority: "P1",
  },
  {
    customerId: "C-10041205",
    customerName: "최하은",
    segment: "잠재",
    ageGroup: "20대",
    branchName: "홍대입구지점",
    assetLevel: "초급",
    recentActivityScore: 82,
    appLoginScore: 95,
    smsResponseScore: 55,
    pushOpenScore: 91,
    tmSuitabilityScore: 38,
    careTaskFeatures: ["마이케어: 첫 주택자금 목표 설정"],
    transactionFeatures: ["최근 앱 접속 빈도 급증", "소액 적금 신규"],
    targetTaskName: "만기·재예치 통합 캠페인 (Q2)",
    targetReason:
      "앱 활동과 푸쉬 오픈이 매우 높아 비대면 채널 중심 캠페인이 적합합니다. 영업점 TM은 우선순위 낮음.",
    featureSummary: "앱활성·푸쉬 우수·청년 세그먼트",
    recommendedChannels: [
      { channel: "앱푸쉬", score: 94, reason: "앱 로그인 활성, 푸쉬 수신동의 및 오픈율 높음" },
      { channel: "SOL배너", score: 89, reason: "앱 내 클릭 기반 유입 기대" },
      { channel: "문자메시지", score: 58, reason: "문자 반응은 평균 수준" },
    ],
    primaryChannel: "앱푸쉬",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 청약 준비, 적금 습관을 함께 만들어요.",
        compliance: "사용가능",
        scheduledDate: "2025-04-03",
        reason: "청년 타깃 템플릿",
        templateId: "MSG-T-2201",
      },
      push: {
        templateOrNew: "기존템플릿",
        title: "청약 D-180 체크",
        body: "자금 준비 현황을 앱에서 점검해 보세요.",
        landingUrl: "https://sol.bank.example/housing/first",
        emoji: "🏠",
        imageInfo: "청년 주거 일러스트 C-3",
        fitScore: 93,
        compliance: "사용가능",
        scheduledDate: "2025-04-03",
      },
      banner: {
        line1: "내 첫 집 준비",
        line2: "적금·청약 한 번에 관리",
        imageLabel: "아파트 실루엣",
        imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&q=80",
        landingUrl: "https://sol.bank.example/youth/housing",
        reason: "청년층 클릭률 상위 배너 세트",
        expectedCtr: "5.8%",
      },
      tm: {
        briefing: "비대면 우선. 필요 시 챗봇/콜 연계.",
        consultPoints: [],
        script: "현재는 앱 안내 위주로 운영합니다.",
        recommendedSms: "",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-03",
    expectedPerformance: "푸쉬 오픈 48% 예상",
    feedbackSignals: ["배너 CTR 높음 → 유사 카피 강화"],
    priority: "P2",
  },
  {
    customerId: "C-10005612",
    customerName: "정우진",
    segment: "VIP",
    ageGroup: "60대",
    branchName: "서초PB센터",
    assetLevel: "초고자산",
    recentActivityScore: 70,
    appLoginScore: 66,
    smsResponseScore: 80,
    pushOpenScore: 58,
    tmSuitabilityScore: 96,
    careTaskFeatures: ["마이케어: 상속/증여 상담 예약 요청"],
    transactionFeatures: ["부동산 관련 자금 이동 증가", "신탁 상품 문의 이력"],
    targetTaskName: "만기·재예치 통합 캠페인 (Q2)",
    targetReason:
      "자금 이동 패턴과 상담 이력으로 복합 자문이 필요합니다. TM 적합도가 매우 높습니다.",
    featureSummary: "자금이동·신탁문의·TM 최우선",
    recommendedChannels: [
      { channel: "영업점TM", score: 97, reason: "고가치, 복합 설명 필요, 최근 상담 이력 존재" },
      { channel: "문자메시지", score: 82, reason: "문자 반응률 우수" },
      { channel: "SOL배너", score: 55, reason: "보조 채널" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] PB 상담 일정 안내드립니다. 담당자 확인 후 연락드리겠습니다.",
        compliance: "사용가능",
        scheduledDate: "2025-04-01",
        templateId: "MSG-T-9901",
      },
      push: {
        templateOrNew: "신규생성",
        title: "상속·증여, 먼저 점검",
        body: "전문 상담 일정을 잡아보세요.",
        landingUrl: "https://sol.bank.example/pb/trust",
        emoji: "📋",
        imageInfo: "다큐먼트 톤 이미지",
        fitScore: 60,
        compliance: "심사필요",
        scheduledDate: "2025-04-10",
      },
      banner: {
        line1: "가문 자산 설계",
        line2: "신탁 전문 PB 상담",
        imageLabel: "클래식 금융",
        imageUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&q=80",
        landingUrl: "https://sol.bank.example/pb",
        reason: "VIP 전용 랜딩과 매칭",
        expectedCtr: "2.9%",
      },
      tm: {
        briefing: "증여세·상속세 이슈 가능성. 신탁 구조와 유동성 동시 고려 필요.",
        consultPoints: ["가족 지분 구조", "증여 시점", "신탁 보수 구조"],
        script:
          "최근 자금 흐름을 보시면서 가문 자산의 방향을 함께 정리해 보고자 합니다. 전문 자문이 필요한 시점으로 보입니다.",
        recommendedSms: "[OO은행] PB 상담 일정 조율 안내",
      },
    },
    complianceStatus: "검토중",
    scheduledDate: "2025-04-01",
    expectedPerformance: "TM 전환 38% 예상",
    feedbackSignals: ["TM 성공 시 신탁 계약 전환"],
    priority: "P1",
  },
  {
    customerId: "C-10036740",
    customerName: "한지우",
    segment: "성장형",
    ageGroup: "30대",
    branchName: "판교테크원지점",
    assetLevel: "중상",
    recentActivityScore: 90,
    appLoginScore: 88,
    smsResponseScore: 76,
    pushOpenScore: 79,
    tmSuitabilityScore: 48,
    careTaskFeatures: ["마이케어: 해외주식 관심 태그"],
    transactionFeatures: ["외화 입출금 증가", "국내 주식 거래 시작"],
    targetTaskName: "만기·재예치 통합 캠페인 (Q2)",
    targetReason:
      "거래 패턴이 해외 자산으로 확장되는 초기 신호입니다. 앱 푸쉬와 배너로 교육 콘텐츠 유입을 유도합니다.",
    featureSummary: "외화↑·주식거래·디지털 친화",
    recommendedChannels: [
      { channel: "SOL배너", score: 91, reason: "앱 활동성 높고 클릭 기반 유입 예상" },
      { channel: "앱푸쉬", score: 88, reason: "푸쉬 수신동의 및 오픈율 양호" },
      { channel: "문자메시지", score: 72, reason: "보조" },
    ],
    primaryChannel: "SOL배너",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 해외투자 시작 전 체크리스트를 보내드립니다.",
        compliance: "사용가능",
        scheduledDate: "2025-04-04",
        templateId: "MSG-T-5512",
      },
      push: {
        templateOrNew: "기존템플릿",
        title: "해외투자 첫걸음",
        body: "환헤지·분산투자 기초를 3분 만에.",
        landingUrl: "https://sol.bank.example/learn/global",
        emoji: "🌐",
        imageInfo: "글로브 아이콘",
        fitScore: 86,
        compliance: "사용가능",
        scheduledDate: "2025-04-04",
      },
      banner: {
        line1: "해외투자, 어디서부터?",
        line2: "기초 가이드 무료 제공",
        imageLabel: "글로벌 맵",
        imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=400&q=80",
        landingUrl: "https://sol.bank.example/global/start",
        reason: "교육형 랜딩과 클릭률 상관 높음",
        expectedCtr: "4.7%",
      },
      tm: {
        briefing: "디지털 우선. 심화 상담은 요청 시.",
        consultPoints: [],
        script: "",
        recommendedSms: "",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-04",
    expectedPerformance: "배너 CTR 4.7% 예상",
    feedbackSignals: ["교육 랜딩 이후 계좌 개설 전환 추적"],
    priority: "P2",
  },
  {
    customerId: "C-10022198",
    customerName: "오세린",
    segment: "휴면위험",
    ageGroup: "40대",
    branchName: "인천송도지점",
    assetLevel: "중간",
    recentActivityScore: 44,
    appLoginScore: 40,
    smsResponseScore: 68,
    pushOpenScore: 35,
    tmSuitabilityScore: 72,
    careTaskFeatures: ["마이케어: 6개월 미거래"],
    transactionFeatures: ["카드 이용 급감", "이체 거래 감소"],
    targetTaskName: "디지털 푸쉬·문자 동시 캠페인",
    targetReason:
      "거래가 줄어 휴면 위험이 있습니다. 문자와 TM 병행으로 관계 회복을 시도합니다.",
    featureSummary: "거래감소·휴면위험·TM 병행",
    recommendedChannels: [
      { channel: "문자메시지", score: 85, reason: "문자 반응은 남아 있음" },
      { channel: "영업점TM", score: 78, reason: "대면 설득 필요 가능성" },
      { channel: "앱푸쉬", score: 40, reason: "오픈율 낮음" },
    ],
    primaryChannel: "문자메시지",
    recommendedContent: {
      sms: {
        templateOrNew: "신규생성",
        message:
          "[OO은행] 오랜만입니다. 고객님께 도움이 될 혜택과 이벤트를 안내드립니다. 수신거부: 무료",
        compliance: "심사필요",
        scheduledDate: "2025-04-06",
        reason: "톤 다운 리인게이지먼트 문구 신규",
      },
      push: {
        templateOrNew: "신규생성",
        title: "다시 찾아주세요",
        body: "맞춤 혜택을 준비했습니다.",
        landingUrl: "https://sol.bank.example/winback",
        emoji: "👋",
        imageInfo: "소프트 일러스트",
        fitScore: 38,
        compliance: "심사필요",
        scheduledDate: "2025-04-12",
      },
      banner: {
        line1: "잠시 멀어졌다면",
        line2: "다시 연결되는 혜택",
        imageLabel: "핸드셰이크",
        imageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=400&q=80",
        landingUrl: "https://sol.bank.example/welcome",
        reason: "윈백 캠페인 유형",
        expectedCtr: "1.9%",
      },
      tm: {
        briefing: "민감한 톤 유지. 불만 VOC 여부 사전 확인.",
        consultPoints: ["이탈 사유 탐색", "수수료 혜택"],
        script: "불편을 드린 점은 없으셨는지 가볍게 여쭙고, 필요 혜택을 맞춤 제안합니다.",
        recommendedSms: "",
      },
    },
    complianceStatus: "심사필요",
    scheduledDate: "2025-04-06",
    expectedPerformance: "문자 응답 9% 예상",
    feedbackSignals: ["휴면 세그먼트는 푸쉬보다 문자 우선"],
    priority: "P3",
  },
  {
    customerId: "C-10048901",
    customerName: "윤채원",
    segment: "안정형",
    ageGroup: "50대",
    branchName: "수원역지점",
    assetLevel: "중상",
    recentActivityScore: 68,
    appLoginScore: 72,
    smsResponseScore: 77,
    pushOpenScore: 70,
    tmSuitabilityScore: 64,
    careTaskFeatures: ["마이케어: 보험 갱신 알림"],
    transactionFeatures: ["보험료 자동이체 정상", "대출 금리 변동 구간"],
    targetTaskName: "디지털 푸쉬·문자 동시 캠페인",
    targetReason:
      "금리 변동 구간에서 상환 구조 점검 니즈가 있습니다. 문자와 푸쉬 병행이 적합합니다.",
    featureSummary: "금리변동·자동이체·안정형",
    recommendedChannels: [
      { channel: "문자메시지", score: 84, reason: "문자 반응률 우수" },
      { channel: "앱푸쉬", score: 80, reason: "푸쉬 오픈 양호" },
      { channel: "SOL배너", score: 70, reason: "앱 활동 중간" },
    ],
    primaryChannel: "문자메시지",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 금리 변동에 따른 상환 계획 점검을 권해 드립니다.",
        compliance: "사용가능",
        scheduledDate: "2025-04-02",
        templateId: "MSG-T-7734",
      },
      push: {
        templateOrNew: "기존템플릿",
        title: "상환 플랜 점검",
        body: "금리 변동 시뮬레이션을 실행해 보세요.",
        landingUrl: "https://sol.bank.example/loan/rate",
        emoji: "📉",
        imageInfo: "차트 다운",
        fitScore: 81,
        compliance: "사용가능",
        scheduledDate: "2025-04-02",
      },
      banner: {
        line1: "금리 변동, 내 상환은?",
        line2: "시뮬레이션으로 확인",
        imageLabel: "금리 그래프",
        imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&q=80",
        landingUrl: "https://sol.bank.example/loan/sim",
        reason: "대출 고객 CTR 높은 유형",
        expectedCtr: "3.4%",
      },
      tm: {
        briefing: "필요 시 상환 방식 변경 상담 연계.",
        consultPoints: ["고정/변동 전환", "중도상환"],
        script: "",
        recommendedSms: "",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-02",
    expectedPerformance: "푸쉬 오픈 36% / 문자 응답 14%",
    feedbackSignals: [],
    priority: "P2",
  },
  {
    customerId: "C-10051233",
    customerName: "강태양",
    segment: "성장형",
    ageGroup: "30대",
    branchName: "부산해운대지점",
    assetLevel: "중간",
    recentActivityScore: 79,
    appLoginScore: 84,
    smsResponseScore: 62,
    pushOpenScore: 88,
    tmSuitabilityScore: 42,
    careTaskFeatures: ["마이케어: 여행 적금 목표"],
    transactionFeatures: ["환전 거래 증가", "체크카드 해외 이용 증가"],
    targetTaskName: "디지털 푸쉬·문자 동시 캠페인",
    targetReason:
      "해외 이용 패턴이 뚜렷해 여행 금융 상품 추천이 적합합니다. 푸쉬와 배너 중심.",
    featureSummary: "환전·해외카드·여행니즈",
    recommendedChannels: [
      { channel: "앱푸쉬", score: 92, reason: "푸쉬 오픈율 높음" },
      { channel: "SOL배너", score: 87, reason: "여행 테마 클릭률 높음" },
      { channel: "문자메시지", score: 65, reason: "보조" },
    ],
    primaryChannel: "앱푸쉬",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 트래블 혜택 업데이트 안내",
        compliance: "사용가능",
        scheduledDate: "2025-04-03",
        templateId: "MSG-T-6612",
      },
      push: {
        templateOrNew: "기존템플릿",
        title: "환전·카드 혜택 한눈에",
        body: "여행 전 체크리스트를 확인하세요.",
        landingUrl: "https://sol.bank.example/travel/pack",
        emoji: "✈️",
        imageInfo: "비행기 일러스트",
        fitScore: 90,
        compliance: "사용가능",
        scheduledDate: "2025-04-03",
      },
      banner: {
        line1: "여행 전 필수 체크",
        line2: "환전·카드 혜택 모음",
        imageLabel: "비치",
        imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80",
        landingUrl: "https://sol.bank.example/travel",
        reason: "시즌성 여행 클릭 상승",
        expectedCtr: "5.1%",
      },
      tm: {
        briefing: "",
        consultPoints: [],
        script: "",
        recommendedSms: "",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-03",
    expectedPerformance: "푸쉬 오픈 44%",
    feedbackSignals: ["여행 배너 CTR 피크 시즌 상향"],
    priority: "P3",
  },
  {
    customerId: "C-10062388",
    customerName: "서지아",
    segment: "VIP",
    ageGroup: "40대",
    branchName: "압구정PB센터",
    assetLevel: "초고자산",
    recentActivityScore: 74,
    appLoginScore: 78,
    smsResponseScore: 82,
    pushOpenScore: 71,
    tmSuitabilityScore: 89,
    careTaskFeatures: ["마이케어: 사모펀드 관심"],
    transactionFeatures: ["펀드 추가 매수", "외화 예금 증액"],
    targetTaskName: "디지털 푸쉬·문자 동시 캠페인",
    targetReason:
      "투자 성향이 공격적으로 이동 중입니다. PB TM과 맞춤 푸쉬 병행.",
    featureSummary: "펀드매수·외화·고자산",
    recommendedChannels: [
      { channel: "영업점TM", score: 93, reason: "고가치, 복합 설명 필요" },
      { channel: "앱푸쉬", score: 84, reason: "심화 콘텐츠 링크 유입" },
      { channel: "SOL배너", score: 68, reason: "보조" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] PB 미팅 일정 제안드립니다.",
        compliance: "사용가능",
        scheduledDate: "2025-04-01",
        templateId: "MSG-T-8810",
      },
      push: {
        templateOrNew: "신규생성",
        title: "대체투자 인사이트",
        body: "전문 리포트를 PB와 함께 살펴보세요.",
        landingUrl: "https://sol.bank.example/pb/alt",
        emoji: "📊",
        imageInfo: "리포트 커버",
        fitScore: 78,
        compliance: "검토중",
        scheduledDate: "2025-04-07",
      },
      banner: {
        line1: "알파를 찾는 투자",
        line2: "PB 인사이트 미리보기",
        imageLabel: "다크 톤 금융",
        imageUrl: "https://images.unsplash.com/photo-1642543495637-2d1f996f3b25?w=400&q=80",
        landingUrl: "https://sol.bank.example/pb/insights",
        reason: "고자산층 전용 카피",
        expectedCtr: "3.8%",
      },
      tm: {
        briefing: "리스크 한도와 유동성 균형을 재점검. 적합성 원칙 준수.",
        consultPoints: ["투자 한도", "환헤지", "세금"],
        script:
          "최근 매수 흐름을 보면 포트폴리오의 공격적 비중이 높아지고 있습니다. 목표 수익률과 변동성 허용 범위를 함께 재정의해 보겠습니다.",
        recommendedSms: "[OO은행] PB 상담 일정 안내",
      },
    },
    complianceStatus: "검토중",
    scheduledDate: "2025-04-01",
    expectedPerformance: "TM 전환 29%",
    feedbackSignals: ["TM 성공 시 사모펀드 설명 만족도 높음"],
    priority: "P1",
  },
  {
    customerId: "C-10073412",
    customerName: "문하람",
    segment: "잠재",
    ageGroup: "20대",
    branchName: "대전둔산지점",
    assetLevel: "초급",
    recentActivityScore: 85,
    appLoginScore: 90,
    smsResponseScore: 58,
    pushOpenScore: 86,
    tmSuitabilityScore: 35,
    careTaskFeatures: ["마이케어: 첫 카드 한도 상향 가능"],
    transactionFeatures: ["급여이체 신규", "신용점수 상승 추정"],
    targetTaskName: "디지털 푸쉬·문자 동시 캠페인",
    targetReason:
      "급여이체가 새로 잡혀 성장형 잠재 고객으로 분류됩니다. 앱 중심 온보딩.",
    featureSummary: "급여이체·신용↑·디지털",
    recommendedChannels: [
      { channel: "SOL배너", score: 90, reason: "온보딩 클릭 유입" },
      { channel: "앱푸쉬", score: 89, reason: "푸쉬 오픈 높음" },
      { channel: "문자메시지", score: 60, reason: "보조" },
    ],
    primaryChannel: "SOL배너",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 직장인 맞춤 혜택을 확인해 보세요.",
        compliance: "사용가능",
        scheduledDate: "2025-04-04",
        templateId: "MSG-T-1102",
      },
      push: {
        templateOrNew: "기존템플릿",
        title: "급여 받은 날 혜택",
        body: "청년 우대 금리·캐시백 확인",
        landingUrl: "https://sol.bank.example/youth/salary",
        emoji: "💼",
        imageInfo: "오피스 미니멀",
        fitScore: 87,
        compliance: "사용가능",
        scheduledDate: "2025-04-04",
      },
      banner: {
        line1: "첫 급여, 첫 금융 습관",
        line2: "우대 조건 한 번에",
        imageLabel: "미니멀 코인 스택",
        imageUrl: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&q=80",
        landingUrl: "https://sol.bank.example/onboarding",
        reason: "온보딩 배너 세트 상위 성과",
        expectedCtr: "6.2%",
      },
      tm: {
        briefing: "",
        consultPoints: [],
        script: "",
        recommendedSms: "",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-04",
    expectedPerformance: "배너 CTR 6.2%",
    feedbackSignals: ["급여이체 신규 → 적금 전환율 추적"],
    priority: "P3",
  },
  {
    customerId: "C-10084556",
    customerName: "배수아",
    segment: "휴면위험",
    ageGroup: "40대",
    branchName: "광주상무지점",
    assetLevel: "중간",
    recentActivityScore: 48,
    appLoginScore: 45,
    smsResponseScore: 63,
    pushOpenScore: 40,
    tmSuitabilityScore: 68,
    careTaskFeatures: ["마이케어: 대출 연체 없음, 이용 저조"],
    transactionFeatures: ["예금 만기 후 미재예치", "앱 미접속 45일"],
    targetTaskName: "TM 우선 상담 과제",
    targetReason:
      "만기 후 자금이 유휴 상태로 오래 방치되었습니다. 문자와 TM으로 재연결.",
    featureSummary: "미재예치·앱휴면·문자 우선",
    recommendedChannels: [
      { channel: "문자메시지", score: 81, reason: "문자 반응 가능성" },
      { channel: "영업점TM", score: 74, reason: "대면 설명 필요 가능" },
      { channel: "앱푸쉬", score: 42, reason: "미접속" },
    ],
    primaryChannel: "문자메시지",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 만기 자금이 안전하게 자리를 찾도록 도와드릴게요.",
        compliance: "사용가능",
        scheduledDate: "2025-04-05",
        templateId: "MSG-T-3309",
      },
      push: {
        templateOrNew: "신규생성",
        title: "유휴 자금 점검",
        body: "맞춤 상품을 추천해 드려요.",
        landingUrl: "https://sol.bank.example/idle",
        emoji: "🔔",
        imageInfo: "벨 아이콘",
        fitScore: 44,
        compliance: "심사필요",
        scheduledDate: "2025-04-11",
      },
      banner: {
        line1: "자금이 쉬고 있나요?",
        line2: "우대 금리 비교",
        imageLabel: "저금통",
        imageUrl: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400&q=80",
        landingUrl: "https://sol.bank.example/save/compare",
        reason: "유휴자금 캠페인",
        expectedCtr: "2.1%",
      },
      tm: {
        briefing: "민감 톤. 강요성 문구 지양.",
        consultPoints: ["재예치 혜택", "세금"],
        script: "만기 이후 자금 운용이 결정되지 않으셨다면, 부담 없는 상품부터 안내드리겠습니다.",
        recommendedSms: "",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-05",
    expectedPerformance: "문자 응답 11%",
    feedbackSignals: [],
    priority: "P3",
  },
  {
    customerId: "C-10095670",
    customerName: "유준호",
    segment: "안정형",
    ageGroup: "50대",
    branchName: "제주시청지점",
    assetLevel: "중상",
    recentActivityScore: 66,
    appLoginScore: 63,
    smsResponseScore: 73,
    pushOpenScore: 55,
    tmSuitabilityScore: 76,
    careTaskFeatures: ["마이케어: 은퇴 준비 모니터링"],
    transactionFeatures: ["연금 인출 시작", "생활비 이체 증가"],
    targetTaskName: "TM 우선 상담 과제",
    targetReason:
      "인출이 시작되어 현금흐름 관리 니즈가 있습니다. TM과 문자 병행.",
    featureSummary: "연금인출·현금흐름·은퇴",
    recommendedChannels: [
      { channel: "영업점TM", score: 85, reason: "복합 설명 필요 가능" },
      { channel: "문자메시지", score: 80, reason: "문자 반응 양호" },
      { channel: "앱푸쉬", score: 58, reason: "보조" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 은퇴 이후 자금 계획 점검 안내",
        compliance: "사용가능",
        scheduledDate: "2025-04-06",
        templateId: "MSG-T-4488",
      },
      push: {
        templateOrNew: "기존템플릿",
        title: "현금흐름 리포트",
        body: "월 지출과 인출액을 함께 봅니다.",
        landingUrl: "https://sol.bank.example/retire/cashflow",
        emoji: "📆",
        imageInfo: "캘린더 차트",
        fitScore: 72,
        compliance: "사용가능",
        scheduledDate: "2025-04-06",
      },
      banner: {
        line1: "은퇴 후 현금흐름",
        line2: "리포트로 한눈에",
        imageLabel: "은퇴 커플",
        imageUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&q=80",
        landingUrl: "https://sol.bank.example/retire",
        reason: "은퇴 세그먼트 반응 중간 이상",
        expectedCtr: "2.7%",
      },
      tm: {
        briefing: "인출액과 생활비의 균형, 물가 상승 대비.",
        consultPoints: ["인출 전략", "안전자산 비중"],
        script: "은퇴 이후 현금흐름이 어떻게 변하는지 함께 점검하고, 부족분을 메울 수 있는 방법을 논의해 보겠습니다.",
        recommendedSms: "[OO은행] 은퇴 자금 점검 안내",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-06",
    expectedPerformance: "TM 상담 완료 40%",
    feedbackSignals: [],
    priority: "P2",
  },
  {
    customerId: "C-10106781",
    customerName: "남기봄",
    segment: "성장형",
    ageGroup: "30대",
    branchName: "대구동성로지점",
    assetLevel: "중간",
    recentActivityScore: 81,
    appLoginScore: 79,
    smsResponseScore: 69,
    pushOpenScore: 74,
    tmSuitabilityScore: 58,
    careTaskFeatures: ["마이케어: 자동이체 한도 증액 가능"],
    transactionFeatures: ["소액 투자성 펀드 보유", "월 적금 증액"],
    targetTaskName: "TM 우선 상담 과제",
    targetReason:
      "적금 증액과 펀드 보유가 동시에 보여 중간 리스크 성향입니다. 앱 푸쉬와 배너가 효율적입니다.",
    featureSummary: "적금↑·펀드보유·성장형",
    recommendedChannels: [
      { channel: "앱푸쉬", score: 86, reason: "오픈율 양호" },
      { channel: "SOL배너", score: 83, reason: "클릭 유입" },
      { channel: "문자메시지", score: 70, reason: "보조" },
    ],
    primaryChannel: "앱푸쉬",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 적금 증액 시 우대 조건을 확인하세요.",
        compliance: "사용가능",
        scheduledDate: "2025-04-07",
        templateId: "MSG-T-5520",
      },
      push: {
        templateOrNew: "기존템플릿",
        title: "한 톤 더 넣으면?",
        body: "우대 금리와 수익 시뮬레이션",
        landingUrl: "https://sol.bank.example/savings/boost",
        emoji: "🪙",
        imageInfo: "코인 스택",
        fitScore: 84,
        compliance: "사용가능",
        scheduledDate: "2025-04-07",
      },
      banner: {
        line1: "적금 한 톤 더",
        line2: "우대 조건 미리보기",
        imageLabel: "코인 그래프",
        imageUrl: "https://images.unsplash.com/photo-1633158829584-23ba92f7c388?w=400&q=80",
        landingUrl: "https://sol.bank.example/savings",
        reason: "적금 캠페인 반복 구매 높음",
        expectedCtr: "4.0%",
      },
      tm: {
        briefing: "",
        consultPoints: [],
        script: "",
        recommendedSms: "",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-07",
    expectedPerformance: "푸쉬 오픈 39%",
    feedbackSignals: [],
    priority: "P3",
  },
  {
    customerId: "C-10117801",
    customerName: "조민서",
    segment: "성장형",
    ageGroup: "30대",
    branchName: "여의도금융센터",
    assetLevel: "중간",
    recentActivityScore: 74,
    appLoginScore: 78,
    smsResponseScore: 76,
    pushOpenScore: 71,
    tmSuitabilityScore: 48,
    careTaskFeatures: ["마이케어: 정기예금 만기 알림 수신"],
    transactionFeatures: ["정기예금 소액 분할 만기", "급여이체 유지"],
    targetTaskName: "만기·재예치 통합 캠페인 (Q2)",
    targetReason:
      "소액 만기가 여러 건 겹치며 재예치 이탈 위험이 있습니다. 통합 안내로 수수료·금리 비교를 제안합니다.",
    featureSummary: "분할만기·재예치·데모추가",
    recommendedChannels: [
      { channel: "문자메시지", score: 84, reason: "만기 문자 반응 이력 있음" },
      { channel: "SOL배너", score: 76, reason: "앱 자주 이용" },
    ],
    primaryChannel: "문자메시지",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 조민서 고객님, 분할 만기 일정을 한눈에 정리해 드립니다.",
        compliance: "사용가능",
        scheduledDate: "2025-04-08",
        templateId: "MSG-DEMO-A1",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-08",
    expectedPerformance: "문자 응답 12% 예상",
    feedbackSignals: [],
    priority: "P2",
  },
  {
    customerId: "C-10117802",
    customerName: "권태희",
    segment: "안정형",
    ageGroup: "50대",
    branchName: "분당정자지점",
    assetLevel: "중상",
    recentActivityScore: 66,
    appLoginScore: 60,
    smsResponseScore: 81,
    pushOpenScore: 52,
    tmSuitabilityScore: 62,
    careTaskFeatures: ["마이케어: 예금 우대 만기 알림"],
    transactionFeatures: ["대액 예금 만기 14일 전", "세금 우대 상품 보유"],
    targetTaskName: "만기·재예치 통합 캠페인 (Q2)",
    targetReason:
      "대액 만기가 임박해 이자 손실·세제 혜택을 동시에 설명할 필요가 있습니다. 문자+TM 병행 후보입니다.",
    featureSummary: "대액만기·세제·데모추가",
    recommendedChannels: [
      { channel: "문자메시지", score: 88, reason: "문자 신뢰도 높음" },
      { channel: "영업점TM", score: 79, reason: "고액 설명 필요" },
    ],
    primaryChannel: "문자메시지",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 권태희 고객님, 만기 자금 우대 조건을 비교해 보세요.",
        compliance: "사용가능",
        scheduledDate: "2025-04-08",
        templateId: "MSG-DEMO-A2",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-08",
    expectedPerformance: "문자 응답 15% 예상",
    feedbackSignals: [],
    priority: "P1",
  },
  {
    customerId: "C-10117803",
    customerName: "오하린",
    segment: "잠재",
    ageGroup: "20대",
    branchName: "홍대입구지점",
    assetLevel: "초급",
    recentActivityScore: 88,
    appLoginScore: 93,
    smsResponseScore: 58,
    pushOpenScore: 90,
    tmSuitabilityScore: 32,
    careTaskFeatures: ["마이케어: 앱 이벤트 참여 이력"],
    transactionFeatures: ["야간 앱 로그인 증가", "푸쉬 수신 동의"],
    targetTaskName: "디지털 푸쉬·문자 동시 캠페인",
    targetReason:
      "야간 앱 활동이 늘어 푸쉬·인앱 배너 반응이 좋을 것으로 예측됩니다. 문자는 보조 채널로만 배정했습니다.",
    featureSummary: "야간앱·푸쉬우선·데모추가",
    recommendedChannels: [
      { channel: "앱푸쉬", score: 94, reason: "푸쉬 오픈률 상위 구간" },
      { channel: "문자메시지", score: 62, reason: "보조" },
    ],
    primaryChannel: "앱푸쉬",
    recommendedContent: {
      push: {
        templateOrNew: "기존템플릿",
        title: "야간 혜택 체크",
        body: "지금 앱에서 맞춤 혜택을 확인하세요.",
        landingUrl: "https://sol.bank.example/night",
        emoji: "🌙",
        imageInfo: "나이트 모드 배너",
        fitScore: 91,
        compliance: "사용가능",
        scheduledDate: "2025-04-09",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-09",
    expectedPerformance: "푸쉬 오픈 45% 예상",
    feedbackSignals: [],
    priority: "P3",
  },
  {
    customerId: "C-10117804",
    customerName: "임도현",
    segment: "VIP",
    ageGroup: "50대",
    branchName: "강남PB센터",
    assetLevel: "초고자산",
    recentActivityScore: 72,
    appLoginScore: 68,
    smsResponseScore: 79,
    pushOpenScore: 60,
    tmSuitabilityScore: 93,
    careTaskFeatures: ["마이케어: 사모펀드 문의 다수"],
    transactionFeatures: ["대체투자 관심 거래", "해외주식 증가"],
    targetTaskName: "TM 우선 상담 과제",
    targetReason:
      "복합 상품 설명과 적합성 점검이 필요한 고가치 고객입니다. TM 스크립트와 브리핑 카드가 자동 생성되었습니다.",
    featureSummary: "고가치·대체투자·TM필수·데모추가",
    recommendedChannels: [
      { channel: "영업점TM", score: 95, reason: "복합 설명·규제 안내 필요" },
      { channel: "문자메시지", score: 78, reason: "일정 조율용" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      tm: {
        briefing: "대체투자 비중 상승 중, 리스크 한도 재확인 권장.",
        consultPoints: ["투자 한도", "세금", "환헤지"],
        script: "임도현 고객님, 최근 포트폴리오 변동을 함께 점검하고자 합니다.",
        recommendedSms: "[OO은행] PB 상담 일정 제안",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-10",
    expectedPerformance: "TM 전환 30% 예상",
    feedbackSignals: [],
    priority: "P1",
  },
  {
    customerId: "C-10117805",
    customerName: "송지원",
    segment: "안정형",
    ageGroup: "40대",
    branchName: "수원광교지점",
    assetLevel: "중상",
    recentActivityScore: 69,
    appLoginScore: 65,
    smsResponseScore: 74,
    pushOpenScore: 58,
    tmSuitabilityScore: 86,
    careTaskFeatures: ["마이케어: 연금 수령 시작"],
    transactionFeatures: ["연금 인출 패턴 변화", "생활비 이체 증가"],
    targetTaskName: "TM 우선 상담 과제",
    targetReason:
      "연금 인출 이후 현금흐름 재설계가 필요합니다. TM 상담으로 목표 금액·기간을 조정하는 시나리오입니다.",
    featureSummary: "연금인출·현금흐름·데모추가",
    recommendedChannels: [
      { channel: "영업점TM", score: 90, reason: "장기 상담 적합" },
      { channel: "문자메시지", score: 76, reason: "예약 링크" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      tm: {
        briefing: "인출액과 생활비 균형, 물가 시나리오 반영.",
        consultPoints: ["인출액 조정", "안전자산"],
        script: "연금 인출 후 현금흐름을 점검해 보고자 연락드렸습니다.",
        recommendedSms: "[OO은행] 연금 상담 안내",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-10",
    expectedPerformance: "TM 완료율 38% 예상",
    feedbackSignals: [],
    priority: "P2",
  },
  {
    customerId: "C-10117806",
    customerName: "안서준",
    segment: "VIP",
    ageGroup: "50대",
    branchName: "압구정PB센터",
    assetLevel: "초고자산",
    recentActivityScore: 77,
    appLoginScore: 72,
    smsResponseScore: 80,
    pushOpenScore: 68,
    tmSuitabilityScore: 90,
    careTaskFeatures: ["마이케어: 가문 자산 문의"],
    transactionFeatures: ["신탁 잔고 증가", "부동산 자금 이동"],
    targetTaskName: "VIP 자산 점검 패키지",
    targetReason:
      "가문 자산·신탁 구조 점검이 주기적으로 필요한 구간입니다. VIP 전용 카피와 PB 일정을 제안합니다.",
    featureSummary: "신탁·가문자산·VIP·데모추가",
    recommendedChannels: [
      { channel: "영업점TM", score: 96, reason: "PB 면담 필수" },
      { channel: "앱푸쉬", score: 72, reason: "리포트 링크" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 안서준 고객님, VIP 자산 점검 일정을 제안드립니다.",
        compliance: "사용가능",
        scheduledDate: "2025-04-11",
        templateId: "MSG-DEMO-D1",
      },
      tm: {
        briefing: "신탁 보수·유동성 점검.",
        consultPoints: ["신탁 구조", "세금"],
        script: "가문 자산 방향을 함께 정리해 보고자 합니다.",
        recommendedSms: "[OO은행] PB 미팅 제안",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-11",
    expectedPerformance: "TM 전환 35% 예상",
    feedbackSignals: [],
    priority: "P1",
  },
  {
    customerId: "C-10117807",
    customerName: "노예진",
    segment: "VIP",
    ageGroup: "40대",
    branchName: "서초PB센터",
    assetLevel: "초고자산",
    recentActivityScore: 75,
    appLoginScore: 70,
    smsResponseScore: 82,
    pushOpenScore: 66,
    tmSuitabilityScore: 88,
    careTaskFeatures: ["마이케어: 해외 자산 비중 경고"],
    transactionFeatures: ["외화 예금 증액", "환율 헤지 문의"],
    targetTaskName: "VIP 자산 점검 패키지",
    targetReason:
      "환율 변동성 확대 구간에서 해외 자산 비중 조정이 필요합니다. VIP 리스크 리포트와 면담을 권장합니다.",
    featureSummary: "환율·해외자산·VIP·데모추가",
    recommendedChannels: [
      { channel: "영업점TM", score: 94, reason: "헤지·파생 설명 필요 가능" },
      { channel: "SOL배너", score: 70, reason: "리포트 다운로드" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      tm: {
        briefing: "환헤지 비율과 통화 분산.",
        consultPoints: ["통화 분산", "파생 한도"],
        script: "최근 환율 변동에 맞춰 해외 자산 비중을 점검하고자 합니다.",
        recommendedSms: "[OO은행] 환율·자산 점검 안내",
      },
    },
    complianceStatus: "검토중",
    scheduledDate: "2025-04-11",
    expectedPerformance: "TM 상담 33% 예상",
    feedbackSignals: [],
    priority: "P1",
  },
  {
    customerId: "C-10117808",
    customerName: "허민재",
    segment: "VIP",
    ageGroup: "60대",
    branchName: "반포PB센터",
    assetLevel: "초고자산",
    recentActivityScore: 71,
    appLoginScore: 64,
    smsResponseScore: 77,
    pushOpenScore: 55,
    tmSuitabilityScore: 91,
    careTaskFeatures: ["마이케어: 상속 상담 예약 대기"],
    transactionFeatures: ["증여 자금 이동 탐지", "가족 계좌 연계"],
    targetTaskName: "VIP 자산 점검 패키지",
    targetReason:
      "증여·상속 이슈가 동시에 포착되었습니다. 법무·세무 연계 면담이 필요한 유형으로 TM 우선입니다.",
    featureSummary: "증여·상속·VIP·데모추가",
    recommendedChannels: [
      { channel: "영업점TM", score: 97, reason: "복합 자문" },
      { channel: "문자메시지", score: 80, reason: "서류 안내" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      tm: {
        briefing: "증여세 신고 일정·신탁 연계 가능성.",
        consultPoints: ["가족 지분", "증여 시점"],
        script: "자금 흐름을 보며 가문 자산 방향을 정리해 보고자 합니다.",
        recommendedSms: "[OO은행] 상속·증여 상담 안내",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-11",
    expectedPerformance: "TM 전환 31% 예상",
    feedbackSignals: [],
    priority: "P1",
  },
  {
    customerId: "C-10117809",
    customerName: "곽영숙",
    segment: "안정형",
    ageGroup: "60대",
    branchName: "일산대화지점",
    assetLevel: "중상",
    recentActivityScore: 63,
    appLoginScore: 58,
    smsResponseScore: 72,
    pushOpenScore: 48,
    tmSuitabilityScore: 78,
    careTaskFeatures: ["마이케어: 은퇴 D-365 알림"],
    transactionFeatures: ["연금 인출 시작 3개월차", "의료비 이체 증가"],
    targetTaskName: "은퇴·노후 자금 점검 (경량)",
    targetReason:
      "은퇴 직후 현금흐름이 설계 대비 빠르게 줄고 있습니다. 인출액·안전자산 비중을 경량 점검합니다.",
    featureSummary: "은퇴직후·현금흐름·데모추가",
    recommendedChannels: [
      { channel: "영업점TM", score: 84, reason: "대면 설명 선호" },
      { channel: "문자메시지", score: 78, reason: "예약 안내" },
    ],
    primaryChannel: "영업점TM",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 곽영숙 고객님, 은퇴 후 자금 흐름 점검을 권해 드립니다.",
        compliance: "사용가능",
        scheduledDate: "2025-04-12",
        templateId: "MSG-DEMO-E1",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-12",
    expectedPerformance: "TM 응답 40% 예상",
    feedbackSignals: [],
    priority: "P2",
  },
  {
    customerId: "C-10117810",
    customerName: "표재혁",
    segment: "안정형",
    ageGroup: "50대",
    branchName: "천안불당지점",
    assetLevel: "중간",
    recentActivityScore: 65,
    appLoginScore: 61,
    smsResponseScore: 70,
    pushOpenScore: 50,
    tmSuitabilityScore: 74,
    careTaskFeatures: ["마이케어: 노후 목표 금액 미달 경고"],
    transactionFeatures: ["적립식 펀드 중단", "생활비 출금 증가"],
    targetTaskName: "은퇴·노후 자금 점검 (경량)",
    targetReason:
      "노후 목표 대비 적립이 둔화되었습니다. 인출 우선순위와 안전자산 재배분을 안내하는 경량 과제입니다.",
    featureSummary: "적립둔화·노후목표·데모추가",
    recommendedChannels: [
      { channel: "문자메시지", score: 82, reason: "문자 응답 양호" },
      { channel: "영업점TM", score: 76, reason: "숫자 상담 필요" },
    ],
    primaryChannel: "문자메시지",
    recommendedContent: {
      sms: {
        templateOrNew: "신규생성",
        message: "[OO은행] 표재혁 고객님, 노후 목표 점검 안내 (수신거부: 무료)",
        compliance: "심사필요",
        scheduledDate: "2025-04-12",
      },
    },
    complianceStatus: "심사필요",
    scheduledDate: "2025-04-12",
    expectedPerformance: "문자 응답 10% 예상",
    feedbackSignals: [],
    priority: "P3",
  },
  {
    customerId: "C-10117811",
    customerName: "차은비",
    segment: "휴면위험",
    ageGroup: "40대",
    branchName: "인천구월지점",
    assetLevel: "중간",
    recentActivityScore: 46,
    appLoginScore: 42,
    smsResponseScore: 66,
    pushOpenScore: 38,
    tmSuitabilityScore: 70,
    careTaskFeatures: ["마이케어: 90일 미앱접속"],
    transactionFeatures: ["이체 건수 감소", "카드 이용 급감"],
    targetTaskName: "휴면 재연결 윈백",
    targetReason:
      "거래·앱 접속이 동시에 감소해 이탈 위험이 있습니다. 민감 톤의 윈백 메시지와 TM 후보로 분류했습니다.",
    featureSummary: "거래감소·휴면위험·데모추가",
    recommendedChannels: [
      { channel: "문자메시지", score: 83, reason: "문자만 반응 가능성" },
      { channel: "영업점TM", score: 72, reason: "대면 회복" },
    ],
    primaryChannel: "문자메시지",
    recommendedContent: {
      sms: {
        templateOrNew: "신규생성",
        message: "[OO은행] 차은비 고객님, 맞춤 혜택을 준비했습니다. (수신거부: 무료)",
        compliance: "심사필요",
        scheduledDate: "2025-04-13",
      },
    },
    complianceStatus: "심사필요",
    scheduledDate: "2025-04-13",
    expectedPerformance: "문자 응답 8% 예상",
    feedbackSignals: [],
    priority: "P3",
  },
  {
    customerId: "C-10117812",
    customerName: "류하준",
    segment: "휴면위험",
    ageGroup: "30대",
    branchName: "부산서면지점",
    assetLevel: "중간",
    recentActivityScore: 52,
    appLoginScore: 48,
    smsResponseScore: 64,
    pushOpenScore: 42,
    tmSuitabilityScore: 66,
    careTaskFeatures: ["마이케어: 장기 미방문"],
    transactionFeatures: ["월 정기 이체 중단", "예금 소액만 유지"],
    targetTaskName: "휴면 재연결 윈백",
    targetReason:
      "정기 이체가 끊기며 관계가 약해지고 있습니다. 부담 없는 혜택·이벤트 중심으로 재연결을 시도합니다.",
    featureSummary: "이체중단·재연결·데모추가",
    recommendedChannels: [
      { channel: "문자메시지", score: 80, reason: "저비용 접점" },
      { channel: "SOL배너", score: 68, reason: "앱 복귀 유도" },
    ],
    primaryChannel: "문자메시지",
    recommendedContent: {
      sms: {
        templateOrNew: "기존템플릿",
        message: "[OO은행] 류하준 고객님, 놓치기 아까운 혜택을 확인해 보세요.",
        compliance: "사용가능",
        scheduledDate: "2025-04-13",
        templateId: "MSG-DEMO-F2",
      },
    },
    complianceStatus: "사용가능",
    scheduledDate: "2025-04-13",
    expectedPerformance: "문자 응답 9% 예상",
    feedbackSignals: [],
    priority: "P3",
  },
];

export const messageLibrary: MessageTemplate[] = [
  {
    templateId: "MSG-T-8821",
    channelType: "문자메시지",
    templateTitle: "VIP 자산 리밸런싱",
    messageBody: "[OO은행] 고객님 맞춤 자산 리밸런싱 안내. 상담 예약: 앱 > 고객센터",
    complianceApproved: true,
    landingUrl: "https://sol.bank.example/premium/rebalance",
    imageType: "N/A",
    tone: "격식·신뢰",
    useCases: ["VIP", "펀드", "리밸런싱"],
  },
  {
    templateId: "MSG-T-4410",
    channelType: "문자메시지",
    templateTitle: "만기 알림 표준",
    messageBody: "[OO은행] 예금 만기가 다가옵니다. 앱에서 비교해 보세요.",
    complianceApproved: true,
    landingUrl: "https://sol.bank.example/maturity",
    imageType: "N/A",
    tone: "간결·안내",
    useCases: ["만기", "재예치"],
  },
  {
    templateId: "PUSH-T-1203",
    channelType: "앱푸쉬",
    templateTitle: "푸쉬_청약 체크",
    messageBody: "청약 D-180 체크 / 자금 준비 현황을 앱에서 점검",
    complianceApproved: true,
    landingUrl: "https://sol.bank.example/housing/first",
    imageType: "일러스트 C-3",
    tone: "친근·짧게",
    useCases: ["청년", "주택"],
  },
];

export const bannerLibrary: BannerAsset[] = [
  {
    bannerId: "BNR-001",
    headlineLine1: "VIP 맞춤 자산 점검",
    headlineLine2: "지금 앱에서 상담을 예약하세요",
    imageLabel: "프리미엄 라운지",
    imageUrl: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&q=80",
    landingUrl: "https://sol.bank.example/vip/lounge",
    themeType: "프리미엄",
    expectedCtr: "4.2%",
  },
  {
    bannerId: "BNR-002",
    headlineLine1: "만기 자금 맞춤 비교",
    headlineLine2: "한 번에 우대 조건 확인",
    imageLabel: "금융 계산기",
    imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&q=80",
    landingUrl: "https://sol.bank.example/compare",
    themeType: "만기",
    expectedCtr: "3.1%",
  },
];

export const campaignPerformance: CampaignPerformance[] = [
  {
    campaignId: "CMP-240315-A",
    channel: "문자메시지",
    targetCount: 12400,
    responseRate: 14.2,
    successRate: 6.8,
    ctr: 9.1,
    conversionRate: 2.3,
    vocSummary: "문구는 명확하나 링크 대비 이탈 다수, 발송 시간대 혼잡",
    improvementAction: "저반응 세그먼트에는 앱푸쉬 우선 추천 가중치 +8%",
  },
  {
    campaignId: "CMP-240315-B",
    channel: "앱푸쉬",
    targetCount: 8200,
    responseRate: 22.5,
    successRate: 11.4,
    ctr: 12.0,
    conversionRate: 4.1,
    vocSummary: "짧은 카피 선호, 랜딩 로딩 속도 VOC",
    improvementAction: "2줄 카피 템플릿 비중 확대, LCP 개선과 연동",
  },
  {
    campaignId: "CMP-240315-C",
    channel: "SOL배너",
    targetCount: 15300,
    responseRate: 18.0,
    successRate: 7.9,
    ctr: 4.6,
    conversionRate: 1.8,
    vocSummary: "이미지-카피 일치도 높을수록 클릭 상승",
    improvementAction: "클릭률 상위 배너 유형을 RAG 추천에 가중",
  },
  {
    campaignId: "CMP-240315-D",
    channel: "영업점TM",
    targetCount: 420,
    responseRate: 68.0,
    successRate: 34.0,
    ctr: 0,
    conversionRate: 28.0,
    vocSummary: "상담 만족도 높음, 일정 조율 이슈",
    improvementAction: "TM 적합 고객 스코어 상향, 스크립트 A/B 반영",
  },
];

export const dashboardSummary = {
  targetsToday: customers.length,
  campaignsPending: 12,
  channelCounts: {
    문자메시지: customers.filter((c) => c.primaryChannel === "문자메시지").length,
    앱푸쉬: customers.filter((c) => c.primaryChannel === "앱푸쉬").length,
    SOL배너: customers.filter((c) => c.primaryChannel === "SOL배너").length,
    영업점TM: customers.filter((c) => c.primaryChannel === "영업점TM").length,
  },
  complianceReview: customers.filter((c) => c.complianceStatus !== "사용가능").length,
  tmPriority: customers.filter((c) => c.tmSuitabilityScore >= 85).length,
  yesterdayResponse: 16.8,
  yesterdaySuccess: 9.2,
};

/** 본 승인 팝업: 비대면(문자·푸쉬·배너) 집계만 표시 */
const pipelineApprovalCustomers = customers.filter(isCentralApprovalCustomer);
const tmSeparateCustomers = customers.filter((c) => !isCentralApprovalCustomer(c));

export const approvalPopupSnapshot = {
  smsCount: pipelineApprovalCustomers.filter((c) => c.primaryChannel === "문자메시지").length,
  pushCount: pipelineApprovalCustomers.filter((c) => c.primaryChannel === "앱푸쉬").length,
  bannerCount: pipelineApprovalCustomers.filter((c) => c.primaryChannel === "SOL배너").length,
  reasonSummary:
    "만기·급여이체·앱활성 신호가 감지되어 비대면 채널 위주로 집행 대상이 구성되었습니다.",
  campaignCount: 12,
};

function stableHash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function pick(seed: string, mod: number): number {
  return stableHash(seed) % mod;
}

/** 최종 승인·집행 후 고객별 결과(데모: 고객 ID 기준 의사 난수) */
function buildPipelineExecutionOutcomes(): PipelineExecutionOutcome[] {
  return pipelineApprovalCustomers.map((c) => {
    const base = `${c.customerId}|${c.primaryChannel}`;
    const rDeliver = pick(`${base}|d`, 100);
    const rEngage = pick(`${base}|e`, 100);
    const ch = c.primaryChannel;

    if (ch === "문자메시지") {
      const delivered = rDeliver < 94;
      const engaged = delivered && rEngage < 58;
      return {
        customerId: c.customerId,
        customerName: c.customerName,
        channel: ch,
        delivered,
        engaged,
        statusLabel: !delivered ? "발송 실패" : engaged ? "수신·읽음" : "수신·미읽음",
        updatedAt: "2025-03-25 09:15",
      };
    }
    if (ch === "앱푸쉬") {
      const delivered = rDeliver < 96;
      const engaged = delivered && rEngage < 64;
      return {
        customerId: c.customerId,
        customerName: c.customerName,
        channel: ch,
        delivered,
        engaged,
        statusLabel: !delivered ? "발송 실패" : engaged ? "수신·오픈" : "수신·미오픈",
        updatedAt: "2025-03-25 09:15",
      };
    }
    const delivered = rDeliver < 98;
    const engaged = delivered && rEngage < 41;
    return {
      customerId: c.customerId,
      customerName: c.customerName,
      channel: ch,
      delivered,
      engaged,
      statusLabel: !delivered ? "노출 실패" : engaged ? "노출·클릭" : "노출·미클릭",
      updatedAt: "2025-03-25 09:15",
    };
  });
}

function rollupOutcomes(
  outcomes: PipelineExecutionOutcome[],
  channel: ChannelType,
  engagementMetricLabel: string
): ChannelExecutionOutcomeRollup {
  const rows = outcomes.filter((o) => o.channel === channel);
  const total = rows.length;
  const deliveredCount = rows.filter((r) => r.delivered).length;
  const engagedCount = rows.filter((r) => r.delivered && r.engaged).length;
  const deliveryRatePct = total ? Math.round((deliveredCount / total) * 1000) / 10 : 0;
  const engagementAmongDeliveredPct = deliveredCount
    ? Math.round((engagedCount / deliveredCount) * 1000) / 10
    : 0;
  return {
    channel,
    total,
    deliveredCount,
    engagedCount,
    deliveryRatePct,
    engagementAmongDeliveredPct,
    engagementMetricLabel,
  };
}

const _pipelineExecutionOutcomes = buildPipelineExecutionOutcomes();

/** 승인·집행 후 수행 결과 리포트 — 실행 승인 화면 하단에서 사용 */
export const pipelineExecutionOutcomeReport: PipelineExecutionOutcomeReport = {
  asOfLabel: "2025-03-25 09:15 기준",
  summaryNote:
    "최종 승인된 비대면 집행 건에 대한 발송·노출·반응 스냅샷입니다. TM 과제는 TM 고객 메뉴에서 별도 집계됩니다.",
  outcomes: _pipelineExecutionOutcomes,
  rollups: [
    rollupOutcomes(_pipelineExecutionOutcomes, "문자메시지", "반응률(발송 성공 건 중)"),
    rollupOutcomes(_pipelineExecutionOutcomes, "앱푸쉬", "오픈률(발송 성공 건 중)"),
    rollupOutcomes(_pipelineExecutionOutcomes, "SOL배너", "클릭률(노출 성공 건 중)"),
  ],
};

/** AI가 새벽 배치로 생성한 오늘의 고객관리 요약 (내레이션용) */
export const aiMorningBrief = {
  generatedAt: "오늘 06:12",
  headline: "AI가 전담 고객을 자동 선별하고, 타겟·채널·콘텐츠·실행 일정까지 연결했습니다.",
  targetNarration: [
    "거래·행동 데이터와 마이케어 과제 이력을 결합해 접촉이 필요한 고객만 골랐습니다.",
    "우선순위는 만기·이탈 위험·고가치 상담이 필요한 순으로 재정렬했습니다.",
  ],
  contentNarration:
    "채널별로는 문자·푸쉬·SOL 배너·영업점 TM에 자동 배정했고, 메시지·배너·스크립트는 라이브러리 매칭 또는 신규 생성 플래그가 붙었습니다.",
  autoExecutionNote:
    "비대면(문자·푸쉬·배너) 승인 후 시스템 집행으로 넘어갑니다. 영업점 TM·TM 우선 상담 과제는 TM 고객 메뉴에서 별도로 확인합니다.",
  channelPlan: [
    {
      channel: "문자메시지",
      count: pipelineApprovalCustomers.filter((c) => c.primaryChannel === "문자메시지").length,
      contentHint: "만기·혜택·리마인드 템플릿 위주, 일부 신규 문구는 준법 심사 대기",
    },
    {
      channel: "앱푸쉬",
      count: pipelineApprovalCustomers.filter((c) => c.primaryChannel === "앱푸쉬").length,
      contentHint: "짧은 카피 + 랜딩 연결, 앱 활성 고객 우선",
    },
    {
      channel: "SOL배너",
      count: pipelineApprovalCustomers.filter((c) => c.primaryChannel === "SOL배너").length,
      contentHint: "이미지·카피 조합 자동 매칭, 클릭 유형 유사도 반영",
    },
    {
      channel: "영업점TM",
      count: tmSeparateCustomers.length,
      contentHint: "브리핑·스크립트는 TM 고객 메뉴에서 확인 (본 승인 제외)",
    },
  ],
};

/** 어제 완료된 과제 성과 — 사용자에게 피드백만 확인시키는 용도 */
export const yesterdayTaskResults = {
  dateLabel: "어제 (영업일 기준)",
  completedTasks: 132,
  responseRate: 16.8,
  successRate: 9.2,
  headline: "어제 수행이 완료된 과제 성과입니다. 확인만 해 주세요.",
  summary:
    "문자는 평균보다 응답이 좋았고, TM은 상담 완료율이 높았습니다. 이 결과는 오늘의 채널 가중치에 이미 반영되었습니다.",
  highlights: [
    { label: "만기·안내 계열 문자", value: "반응률 14.2%" },
    { label: "앱 푸쉬", value: "오픈률 22.5%" },
    { label: "TM 상담", value: "성공 전환 28%" },
  ],
  userActionHint: "조치가 필요한 항목은 없습니다. 상세는 성과 분석에서 언제든 열람할 수 있습니다.",
};

/** 피드백 루프: 반응↑·목표 성과 미도달 고객 샘플(실제 고객 ID와 매칭 가능) */
export const feedbackFollowUpCustomers: FeedbackFollowUpCustomer[] = [
  {
    customerId: "C-10028491",
    customerName: "김서연",
    segment: "VIP",
    primaryChannel: "영업점TM",
    responseDetail: "TM 상담 완료·펀드 설명 만족 VOC",
    unconvertedReason: "당일 계약 서류 미제출(심사 대기 이탈)",
    nextTargetTag: "RULE_VIP_FUND_RECALL_14D",
    branchQueueTask: "PB 후속 상담(서류·한도 재안내)",
    targetDbField: "SEG_HOT_REACT_NO_CONV_2025Q2",
  },
  {
    customerId: "C-10084556",
    customerName: "배수아",
    segment: "휴면위험",
    primaryChannel: "문자메시지",
    responseDetail: "문자 링크 클릭·앱 재설치",
    unconvertedReason: "재예치 상품 미선택(장바구니 이탈)",
    nextTargetTag: "RULE_IDLE_MSG_RECLICK_7D",
    branchQueueTask: "만기 재연결 콜·TM 보조 과제",
    targetDbField: "FLAG_REACTIV_RECLICK_NO_DEP",
  },
  {
    customerId: "C-10051233",
    customerName: "강태양",
    segment: "성장형",
    primaryChannel: "앱푸쉬",
    responseDetail: "푸쉬 오픈·여행 랜딩 체류·배너 연쇄 클릭",
    unconvertedReason: "추가 상품 체결 없음(혜택만 조회)",
    nextTargetTag: "RULE_TRAVEL_PACK_CROSS_SELL_5D",
    branchQueueTask: "트래블 패키지 재안내·문자 보조 발송",
    targetDbField: "SEG_PUSH_ENGAGE_NO_ACCT",
  },
  {
    customerId: "C-10036740",
    customerName: "한지우",
    segment: "성장형",
    primaryChannel: "SOL배너",
    responseDetail: "배너 CTR 상위·교육 랜딩 체류",
    unconvertedReason: "실계좌 개설·거래 전환 미완료",
    nextTargetTag: "RULE_BANNER_CTR_LOOKALIKE",
    branchQueueTask: "해외투자 교육 후속·TM 또는 전화 재컨택",
    targetDbField: "ATTR_BANNER_HIGH_CTR_DROP",
  },
  {
    customerId: "C-10095670",
    customerName: "유준호",
    segment: "안정형",
    primaryChannel: "영업점TM",
    responseDetail: "연금 인출 상담·시나리오 동의",
    unconvertedReason: "인출액 조정 상품 미체결(가족 협의 대기)",
    nextTargetTag: "RULE_PENSION_FOLLOWUP_21D",
    branchQueueTask: "가족 동반 상담 예약·TM 2차 스크립트",
    targetDbField: "SEG_PENSION_ADVICE_NO_PRODUCT",
  },
  {
    customerId: "C-10117803",
    customerName: "오하린",
    segment: "잠재",
    primaryChannel: "앱푸쉬",
    responseDetail: "야간 푸쉬 오픈·혜택 알림 수신",
    unconvertedReason: "실제 거래·이체 트리거 없음",
    nextTargetTag: "RULE_NIGHT_PUSH_TO_SMS_BRIDGE",
    branchQueueTask: "첫 거래 미션·문자 교차 캠페인",
    targetDbField: "FLAG_YOUNG_ENGAGE_NO_TXN",
  },
  {
    customerId: "C-10117804",
    customerName: "임도현",
    segment: "VIP",
    primaryChannel: "영업점TM",
    responseDetail: "대체투자 설명·리스크 동의",
    unconvertedReason: "내부 한도·적합성 재검토로 계약 보류",
    nextTargetTag: "RULE_ALT_INV_SUITABILITY_RECHECK",
    branchQueueTask: "준법 동반 재상담·서류 보완 리스트",
    targetDbField: "SEG_ALT_INV_PENDING_COMPLIANCE",
  },
  {
    customerId: "C-10117805",
    customerName: "송지원",
    segment: "안정형",
    primaryChannel: "영업점TM",
    responseDetail: "연금 인출 상담·생활비 시뮬레이션",
    unconvertedReason: "안전자산 배분안만 수령·계약 미체결",
    nextTargetTag: "RULE_ANNUITY_SOFT_COMMIT_10D",
    branchQueueTask: "안전자산 재안내·전화 재컨택 과제",
    targetDbField: "SEG_ANNUITY_ADVICE_NO_CLOSE",
  },
];

export const feedbackLoopSummary = {
  followUpSampleCount: feedbackFollowUpCustomers.length,
  pendingDbBatch: 5,
  branchQueueOpen: 12,
  lastBatchLabel: "2025-04-02 새벽 배치",
};
